package dev.cauce.memory.tenant;

import dev.cauce.core.tenant.Tier;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;

/**
 * JPA persistence mapping for a tenant row. This is an infrastructure detail of
 * cauce-memory; the domain type is {@link dev.cauce.core.tenant.Tenant}. Conversion
 * between the two is done by {@link TenantMapper}.
 *
 * <p>The id is assigned by the application (UUIDv7), not generated by the database,
 * so there is no {@code @GeneratedValue}.
 */
@Entity
@Table(name = "tenants")
public class TenantEntity {

    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Column(name = "parent_tenant_id")
    private UUID parentTenantId;

    @Enumerated(EnumType.STRING)
    @Column(name = "tier", nullable = false, length = 20)
    private Tier tier;

    @Column(name = "name", nullable = false, length = 200)
    private String name;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected TenantEntity() {
        // for JPA
    }

    public TenantEntity(UUID id, UUID parentTenantId, Tier tier, String name,
                        Instant createdAt, Instant updatedAt) {
        this.id = id;
        this.parentTenantId = parentTenantId;
        this.tier = tier;
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UUID getId() {
        return id;
    }

    public UUID getParentTenantId() {
        return parentTenantId;
    }

    public Tier getTier() {
        return tier;
    }

    public String getName() {
        return name;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
